[package]
name = "factorio_utils"
version = "0.1.0"
authors = ["Jack Firth <jackhfirth@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.0"
flate2 = "1.0.6"
serde = "1.0.85"
serde_derive = "1.0"
serde_json = "1.0"
