version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Install
          command: cargo install --path .
      - run:
          name: Build
          command: cargo build --path .
      - run:
          name: Test
          command: cargo test --path .
